apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: workshop
  labels:
    app: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-deployment

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1

  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
      - name: frontend
        image: iamamash/three-tier-app-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://10.100.52.158:3500/api/tasks"
