apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: workshop
spec:
  selector:
    app: frontend-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

