apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: workshop
spec:
  selector:
    app: backend-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3500
  type: ClusterIP
