apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: workshop
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/d

