apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: workshop
spec:
  selector:
    app: mongo-deployment
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP

